---
title: '20200318'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##安裝package
```{r}
install.packages(c("dplyr", "lubridate", "googlesheets4"))
```

##執行package
```{r}
library(googlesheets4)
library(lubridate)
library(dplyr)
```


##creat object
```{r}
a <- 2
a = 2 # = 與 <-同義
```
```{r}
3 -> b
```

```{r}
a
```

```{r}
my_108_total_credits <- 15
_108_total_credits <- 15
108_total_credits <- 15
_my_108_total_credits <- 15
my.108.total_credits <- 15
.108.total_credits <- 15 # 隱藏變數
.my.108.total_credits <- 15
我的108學年總學分數 <- 15
`我的108學年總學分數` <- 15 # 特殊名稱處理，`不是名稱的一部份
`.108.total_credits` <- 15
```

```{r}
`我的年紀`<-20
my_age<-`我的年紀`
```

```{r}
library(readr)
A02_company_all_public <- read_csv("https://www.dropbox.com/s/rtz2a9na62n3a8l/A02_company_all_public.csv?dl=1")
A02_company_all_public$`候選人` -> candidate
```




##Atomic vector

```{r}
num1 <- 5
vNum1 <- c(2,5)
vNum2 <- c(2, num1)
#右邊的num1是在 call num1，會得到5，相當於
vNum2<-c(2,5)
```


```{r}
vNum1 <- c(-1,5)
vNum2 <- c(2,3)
vNum3 <- c(vNum1,vNum2)
vNum4 <- c(-1,5,2,3)
vNum5 <- c(c(-1,5),c(2,3))
```


```{r}
vNum1 <- c(-1,5)
vNum2 <- c(2,3)
vNum4 <- c() # 空向量
```


```{r}
vNum3 <- c(vNum2, vNum1)
vNum4 <- c(vNum4, vNum1) # 向量疊代 （recursive vector concatenate）
```

##Different types

###Numeric
```{r}
num1<-5 # 非整數
num2<-5L # 整數

num1Vector<-c(5,6,7)
num2Vector<-c(5L,6L,7L)
```

```{r}
typeof(num1Vector)
typeof(num2Vector)
```


###Character
```{r}
char1<-"你好"
char2<-'你好'
```

他說:"今天多了一個確診"

```{r}
Hesaid<-'他說:"今天多了一個確診"'
```

```{r}
char1Vector<-c("你好","How are you?")
```

```{r}
class(char1Vector)
```
```{r}
dialogue<-c('小明說:"明天不用上課。"','小花說:"真的嗎?"')
cat(dialogue,sep="\n")
```


```{r}
library(httr)
library(dplyr)
GET("https://api.github.com/repos/lyx231/108-2-56-inclass-practice/commits") %>%
  content() %>%
  View()
```



```{r}
library(googlesheets4)
`出席狀況表單網址`<-"https://docs.google.com/spreadsheets/d/1EAG49qDKPWWi0ebkVr29TLrvVnoBPfkvxYY-J3xLAHY/edit#gid=1385433348"
ss <- as_sheets_id(`出席狀況表單網址`)
homework_sheet <- read_sheet(ss)
```

##logics
```{r}
logi1 <- c(T,TRUE,F,FALSE,FALSE)
```

```{r}
sum(logi1)
```

```{r}
num <- c(1.5, 2, 3)
int <- c(1L, 3L, -2L)
char <- c("1.5","2","3")
logi <- c(T,T,F)

typeof(num)
typeof(int)
typeof(char)
typeof(logi)
```
```{r}
class(num)
class(int)
class(char)
class(logi)
```





###Extend atomic vectirs


```{r}
# 10位學生的主系
majors10_char <- c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')

typeof(majors10_char)
class(majors10_char)
```


```{r}
majors10_factor <- factor(majors10_char)
# 或
majors10_factor <- factor(
  c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')
)

typeof(majors10_factor)
class(majors10_factor)
```
```{r}
majors10_char
```
```{r}
majors10_factor
```



```{r}
levels(majors10_factor)
```

##cladd/type conversion
```{r}
stringInteger <- c("1","2","-11")
class(stringInteger) # 無法進行數值運算
stringInteger+2
```

```{r}
stringInteger <- c("1","2","-11")
class(stringInteger) # 無法進行數值運算
numericInteger<-as.numeric(stringInteger)
numericInteger+2
```
```{r}
studentId <- c(410773002, 410773015)
class(studentId)
studentId<-as.character(studentId) #要改變物件本身，一定要回傳到物件
```


##Data/Time

```{r}
browseURL("https://docs.google.com/spreadsheets/d/1EAG49qDKPWWi0ebkVr29TLrvVnoBPfkvxYY-J3xLAHY/edit#gid=458686645")
```
```{r}
library(lubridate)
```

台北 2020-03-18 13:52:40
```{r}
tpeDateTime<-ymd_hms("2020-03-18 13:52:40",tz="Asia/Taipei")
tpeDateTime
class(tpeDateTime)
typeof(tpeDateTime)
```


葡萄牙 Mar.18, 2020, 05:52:40
```{r}
pgDateTime<-mdy_hms("Mar.18, 2020, 05:52:40",tz="Europe/Lisbon")
typeof(pgDateTime)
as.double(tpeDateTime)
as.double(pgDateTime)
```


###轉成同時區
```{r}
with_tz(tpeDateTime, tzone="UTC")
with_tz(pgDateTime, tzone="UTC")
```
```{r}
ymd_hms("2020-03-04T06:56:29Z")
#TZ夾數字代表UTC時間,不用指定時區
with_tz(ymd_hms("2020-03-04T06:56:29Z"),tzone="Asia/Taipei")
```
```{r}
studentTime<-c(ymd_hms("2020-03-04T06:56:29Z"),
               ymd_hms("2020-03-11 14:16:43",tz="Asia/Taipei"),
               ymd_hms("2020-03-11 14:34:33",tz="Asia/Taipei")
               )
studentTime
```
```{r}
with_tz(studentTime,tzone="Europe/Paris")
```

##List

```{r}
vectorExample<-c(2,6,7)
listExample<-list(2,6,7)

print(vectorExample)
print(listExample)
```

每個元素值可以是不同type的物件值
```{r}
#用vector儲存
c("2020-03-31T13:40:55Z",
  "一芳",
  "2",
  "水果茶")

#用list儲存
library(lubridate)
`小明交易1` <- list(
  ymd_hms("2020-03-31T13:40:55Z"), # Date/Time class
  "一芳", # character
  2, # numeric
  "水果茶" # character
)
print(`小明交易1`)
```

物件值可以是vector形式，也可以list
```{r}
#用vector
c(
  c("108學年第1學期","高級會計學","高等統計學"), #向量1
  c("108學年第2學期","食在拉丁美洲") #向量2
)
```

```{r}
#用list
list(
  c("108學年第1學期","高級會計學","高等統計學"), #向量1
  c("108學年第2學期","食在拉丁美洲") #向量2
)
```
```{r}
# list含兩個vectors
`小明108學年課表A` <- list(
  c("108-1","高級會計學","高等統計學"),
  c("108-2","食在拉丁美洲")
)
print(`小明108學年課表A`)
```
```{r}
# list含兩個lists
`小明108學年課表B` <- list(
  list("108-1","高級會計學","高等統計學"),
  list("108-2","食在拉丁美洲")
)
print(`小明108學年課表B`)
```
```{r}
# list含兩個lists, 子層list又各含兩個vectors
`小明108學年課表C` <- list(
  list(
    c("108-1"), # 可只寫 "108-1"
    c("高級會計學","高等統計學")
       ),
  list(
    c("108-2"),
    c("食在拉丁美洲")
  )
)
print(`小明108學年課表C`)
```
物件值可以取名
```{r}
# list含兩個lists, 子層list又各含兩個vectors
`小明108學年課表D` <- list(
  `108學年第1學期`=list(
    c("108-1"), # 可只寫 "108-1"
    c("高級會計學","高等統計學")
       ),
  `108學年第2學期`=list(
    c("108-2"),
    c("食在拉丁美洲")
  )
)
print(`小明108學年課表D`)
```

##Github Commit

```{r}
commit<-list(
  author=
)
```













